### ISSUE TITLE
CCSDS SLE ASN.1 compilation

### ISSUE THREAD

**Issue by xpromache** [gabhijit/hampi#65]
I am trying to compile the ASN.1 files from here:
 https://github.com/yamcs/jsle/tree/master/src/main/asn.1

but the hampi-rs-asn1c never finishes and stays in top with 100% cpu consumption.

The files have been copied manually from the CCSDS SLE specs and they do compile to java using this tool: https://www.beanit.com/asn1/

(in addition to this, I also need the BER encoding for implementing that SLE protocols but one issue at a time...)

**Comment by gabhijit** [comment]
@xpromache : Thanks for reporting this. Currently the ASN.1 tags are not handled in the compiler. This is because the codecs that I was interested in initially didn't need those. The error occurs because of unhandled tags. 

Immediately, will fix this in the compiler, but actually supporting the tags properly and codecs like BER might be some time away. 

Related: I realized there is not enough debugging support in the compiler, which makes it a little annoying to use because one cannot report the 'actual' bug and a simple test cases for such buggy situations. Will add that first. 

Happy to merge a PR if you can send one for tags support and/or BER codec.

**Comment by xpromache** [comment]
@gabhijit sorry for the delay, I'm new to both Rust and ASN.1.
I'm looking to add tag support: should I make in parser/asn/struct/types/mod.rs a new enum Asn1Class and a struct Asn1Tag:

```
enum Asn1Class {
  Universal,
  Application,
  ContextSpecific,
  Private
}

 struct Asn1Tag {
   class: Asn1Class,
   number: u32
} 

```
and then augment the struct Asn1Type with a tag: Option<Asn1Tag> field?

**Comment by gabhijit** [comment]
@xpromache : Sorry even I didn't get a chance to look at this. I was busy adding features to the crate which I needed for my other project. 
 
I believe, you are on the right path. I myself have not read the specification related to tags fully well. Many parts of the code I have not visited for little over a year, so it might be so that I may miss something. Here is how I foresee it could go - 
1. The tags are associated during the parsing phase (here one has to take into consideration the module level `IMPLICIT`, `EXPLICIT` etc. This would probably mean we will need to have either that information handy during parsing (ie. somewhere in the `parse_definition` (inside `src/parser/asn/defs.rs`) that would mean passing a ref or a `mut` ref for the `Asn1Module` to `parse_definition` (passing `mut ref` should be okay since we are going to be parsing at most one definition at a time). This change is likely to touch many (if not all) files in the `parser` module. 
2. Then you could add the option in the `Asn1Type` struct (which is returned I believe as a result of parsing a type). 
3. Eventually this should also go in the `Asn1ResolvedType` (this is what is used for generating the code), it can most likely be copied from the `Asn1Type` above.
4. Finally during code generation I am expecting something like following attribute `[asn(tag = (application, 0)]` on the generated structures and/or Enums. 
5. Addition of this `asn` tag can itself be controlled (ideally should) through a CLI switch (something like `--tags`) (inside `asn1-compiler` crate.) 
6. This `tag` will be used by the actual `BER` codec in the `asn1_codecs` and `asn1_codecs_derive`.

This is a rough sketch.  We can do this as a part of multiple PRs. First getting the `parsing` and tag assignment part right would be a great thing to have! 

Hope this helps! 

Thanks a lot for trying to give it a shot.

**Comment by gabhijit** [comment]
@xpromache : Since we have a proper tracking task for BER codec support (#75), I believe this issue can be closed now.

**Comment by xpromache** [comment]
Ok, we can close in favor of #75 and #79
